### ISSUE TITLE
Dusha dataset

### ISSUE THREAD

**Issue by nshmyrev** [emo-box/EmoBox#6]
Hey, nice repo. I see you miss a big Russian emotion dataset Dusha

https://github.com/salute-developers/golos/tree/master/dusha#dusha-dataset

consider integrating it please

**Comment by ddlBoJack** [comment]
Hi, thank you for the proposal! We will consider adding it in the future(and welcome PR). Now there is a Russian SER dataset named RESD in our benchmark, which may help.
